version: '3'

services:
    mysql-app:
        image: mysql:5.7.22
        ports:
          - "3306:3306"
        environment:
          MYSQL_USER: root
          MYSQL_DATABASE: bot_instagram
          MYSQL_ROOT_PASSWORD: root
        volumes:
          - .docker/dbdata:/var/lib/mysql
        networks:
          - bot-network

networks:
    bot-network:
        driver: bridge